"""empty message

Revision ID: d06f6019ccbe
Revises: 
Create Date: 2020-11-16 23:36:23.436082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06f6019ccbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('in_bag', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('story', sa.String(length=500), nullable=True),
    sa.Column('image1', sa.String(length=100), nullable=True),
    sa.Column('image2', sa.String(length=100), nullable=True),
    sa.Column('image3', sa.String(length=100), nullable=True),
    sa.Column('image4', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('customer_email_address', sa.String(length=150), nullable=False),
    sa.Column('customer_delivery_address', sa.String(length=500), nullable=False),
    sa.Column('products', sa.String(), nullable=False),
    sa.Column('order_amount_total', sa.String(length=100), nullable=False),
    sa.Column('checkout_session_id', sa.String(length=200), nullable=False),
    sa.Column('payment_intent_id', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_session_id'),
    sa.UniqueConstraint('payment_intent_id')
    )
    op.create_table('poster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('display_title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('story', sa.String(length=500), nullable=True),
    sa.Column('large', sa.String(length=150), nullable=True),
    sa.Column('medium', sa.String(length=150), nullable=True),
    sa.Column('small', sa.String(length=150), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poster')
    op.drop_table('order')
    op.drop_table('artwork')
    # ### end Alembic commands ###
